name: Report gas diff

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"

jobs:
  compare_gas_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: forge test --gas-report > gasreport.ansi

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3.7
        with:
          workflowId: foundry-gas-diff.yml
          ignore: test/**/*
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: ${{ !steps.gas_diff.outputs.markdown }} # delete the comment in case changes no longer impacts gas costs
          message: ${{ steps.gas_diff.outputs.markdown }}
